<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Weave</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>$(MSBuildThisFileDirectory)..\resources\weave.ico</ApplicationIcon> 
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>Weave</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\templates\CMakeLists.txt">
      <Link>Resources/templates/CMakeLists.txt</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\main.cpp">
      <Link>Resources/templates/main.cpp</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\user_project.hpp">
      <Link>Resources/templates/user_project.hpp</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\.gitignore">
      <Link>Resources/templates/.gitignore</Link>
    </EmbeddedResource>

    <EmbeddedResource Include="..\..\templates\cmake\mayaflux.cmake">
      <Link>Resources/templates/cmake/mayaflux.cmake</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\cmake\shaders.cmake">
      <Link>Resources/templates/cmake/shaders.cmake</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\cmake\build_community.cmake">
      <Link>Resources/templates/cmake/build_community.cmake</Link>
    </EmbeddedResource>

    <EmbeddedResource Include="..\..\templates\community\module.cmake">
      <Link>Resources/templates/community/module.cmake</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\community\community.json">
      <Link>Resources/templates/community/community.json</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\community\test\CMakeLists.txt">
      <Link>Resources/templates/community/test/CMakeLists.txt</Link>
    </EmbeddedResource>

    <EmbeddedResource Include="..\..\templates\vscode\settings.json">
      <Link>Resources/templates/vscode/settings.json</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\vscode\tasks.json">
      <Link>Resources/templates/vscode/tasks.json</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\templates\vscode\launch.json">
      <Link>Resources/templates/vscode/launch.json</Link>
    </EmbeddedResource>

    <EmbeddedResource Include="..\..\templates\shaders\**\*">
      <Link>Resources/templates/shaders/%(RecursiveDir)%(Filename)%(Extension)</Link>
    </EmbeddedResource>
  </ItemGroup>

    <ItemGroup>
    <Content Include="..\..\windows\resources\weave.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
