<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Weave</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>Weave</RootNamespace>
  </PropertyGroup>

<ItemGroup>
  <EmbeddedResource Include="..\..\templates\**\*">
    <Link>Resources/templates/%(RecursiveDir)%(Filename)%(Extension)</Link>
  </EmbeddedResource>
</ItemGroup>

  <ItemGroup>
    <None Include="..\scripts\install_package.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>scripts\install_package.ps1</Link>
    </None>
    <None Include="..\scripts\packages.psd1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>scripts\packages.psd1</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>