[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "weave"
version = "0.4.0"
description = "MayaFlux installer and project creator for Linux"
requires-python = ">=3.8"
dependencies = ["PyGObject"]

[project.scripts]
weave-installer = "lib.main:main"
weave = "lib.cli:main"

[tool.setuptools]
packages = ["lib", "lib.modes", "lib.ui"]

[tool.setuptools.package-dir]
"" = "."

[tool.setuptools.package-data]
lib = ["ui/dark.css"]

[tool.pyright]
typeCheckingMode = "off"

[tool.ruff]
select = ["E", "F"]
ignore = ["E402", "E501"]
